export const projects = [
  {
    id: 'hadiel',
    title: 'Hadiel Health Admin',
    category: 'Web App',
    tags: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    description: 'Admin dashboard for a health tech startup — dynamic routing for enrollment pages, tab-based table views, and custom hooks for clean architecture.',
    year: '2025',
    color: '#7FFFD4',
    featured: true,
    github: 'https://github.com/odinaka',
    live: '#',
    emoji: '🏥',
  },
  {
    id: 'kino',
    title: 'Kino Movie App',
    category: 'Web App',
    tags: ['React', 'Framer Motion', 'Swiper.js', 'Tailwind'],
    description: 'Cinematic movie discovery app with a crossfading hero slideshow, Watchlist & Favourites, and immersive animated transitions.',
    year: '2024',
    color: '#FF8C69',
    featured: true,
    github: 'https://github.com/odinaka',
    live: '#',
    emoji: '🎬',
  },
  {
    id: 'invoice',
    title: 'Invoice Manager',
    category: 'Web App',
    tags: ['React', 'TypeScript', 'Vite'],
    description: 'Full CRUD invoice management system with layout, state management, and filtering — built to production polish.',
    year: '2025',
    color: '#C4B5FD',
    featured: false,
    github: 'https://github.com/odinaka',
    live: '#',
    emoji: '🧾',
  },
  {
    id: 'soen',
    title: 'Shades of Everything Nice',
    category: 'Business',
    tags: ['Meta Ads', 'E-commerce', 'Branding'],
    description: 'Built and operate a registered accessories brand — handling Meta ad campaigns, order management, and business finances from scratch.',
    year: '2024',
    color: '#F9A8D4',
    featured: false,
    github: null,
    live: '#',
    emoji: '🕶️',
  },
  {
    id: 'myhealth',
    title: 'MyHealth Medications Screen',
    category: 'Mobile',
    tags: ['React Native', 'TypeScript', 'API'],
    description: 'Medications screen with date classification logic and timezone-aware parsing for a wellness app. Built on the esther/medications branch.',
    year: '2025',
    color: '#6EE7B7',
    featured: false,
    github: 'https://github.com/odinaka',
    live: null,
    emoji: '💊',
  },
];

export const skills = [
  { name: 'React', level: 90 },
  { name: 'TypeScript', level: 80 },
  { name: 'Next.js', level: 75 },
  { name: 'Tailwind CSS', level: 92 },
  { name: 'Svelte', level: 60 },
  { name: 'Framer Motion', level: 78 },
  { name: 'Vite', level: 85 },
  { name: 'React Native', level: 65 },
  { name: 'GSAP', level: 70 },
  { name: 'Git', level: 82 },
];

export const techMarquee = [
  'React', 'TypeScript', 'Next.js', 'SvelteKit', 'Tailwind CSS',
  'Framer Motion', 'GSAP', 'Vite', 'React Native', 'Git',
  'Node.js', 'REST APIs', 'Figma', 'Vercel', 'HTML5', 'CSS3',
];
